import { build } from 'esbuild';
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
const browser=[process.env.CHROME_PATH,'C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(p=>p&&existsSync(p));
if(!browser)throw new Error('Chrome/Edge unavailable; set CHROME_PATH to run this browser check.');
mkdirSync('.test-build',{recursive:true});
await build({entryPoints:['tests/theme-preview.ts'],outfile:'.test-build/theme-preview.js',bundle:true,platform:'browser',alias:{obsidian:resolve('tests/obsidian-stub.ts')}});
writeFileSync('.test-build/theme-preview.html','<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="../styles.css"><style>body{font-family:Arial;margin:20px;display:grid;grid-template-columns:repeat(4,260px);gap:12px;background:#bbb}section{padding:16px;height:170px;box-sizing:border-box}section.light{background:#fff;--text-normal:#20252c;--background-primary:#fff;color:#20252c}section.dark{background:#202020;--text-normal:#dcddde;--background-primary:#202020;color:#dcddde}h2{font-size:15px}p{font-size:12px}.frame{height:145px;padding-top:12px}.world{position:relative;transform-origin:0 0}.canvas-node,.canvas-node-group{position:relative;box-sizing:border-box;border:4px solid #718bc0;background:rgba(120,150,190,.15)}.canvas-node-container{position:absolute;inset:0}.canvas-group-label{position:absolute;top:0;left:0;font-size:24px}pre{grid-column:1/5;font-size:10px;white-space:pre-wrap}</style><script defer src="theme-preview.js"></script>');
const result=spawnSync(browser,['--headless','--disable-gpu','--no-first-run','--no-default-browser-check','--disable-background-networking','--user-data-dir='+resolve('.test-build/browser-profile'),'--window-size=1150,1900','--virtual-time-budget=10000','--screenshot='+resolve('.test-build/phase15-themes.png'),'--dump-dom',pathToFileURL(resolve('.test-build/theme-preview.html')).href],{encoding:'utf8',timeout:120000,maxBuffer:10*1024*1024});
if(result.error)throw result.error;
const match=result.stdout.match(/<pre id="results">([\s\S]*?)<\/pre>/);
if(!match)throw new Error('Browser returned no test results: '+result.stderr.slice(-500));
const results=JSON.parse(match[1]);writeFileSync('.test-build/phase15-themes.json',JSON.stringify(results,null,2));
console.log(JSON.stringify(results,null,2));if(results.some(r=>!r.passed))process.exitCode=1;
